name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4  
    
    - name: python install
      uses: actions/setup-python@v2  
      with:
        python-version: '3.x'
    
    - name: create env
      run: make init
    
    - name: Install dependencies
      run: make install

    - name: test
      run: make test

    - name: Run
      run: make run
    
    - name: build-container
      run: make build
